### ISSUE TITLE
Book cover images links seem to be broken

### ISSUE THREAD

**Issue by christopher-caldwell** [merewif/star-wars-loretracker#28]
![image](https://github.com/merewif/star-wars-loretracker/assets/62559469/e8dac81d-b36b-4efc-8071-569247131370)

**Comment by merewif** [comment]
Hey, yeah unfortunately I'll have to replace the sources for all the book covers (and probably comic covers too). I have it on my to do list but I cant tell you when it will be fixed cuz there are close to a thousand of them.

**Comment by merewif** [comment]
Actually if someone wants to make **$20** I set up a bounty for it here:

https://gitpay.me/#/task/669/book-cover-images-links-seem-to-be-broken

The task is considered completed if the image links for each element in the json files below point to the correct image file that corresponds to the title and issue of the publication. The images can be hosted on GitHub, Cloudflare images, S3 buckets or anywhere you prefer as long as they are publically available. 

[Canon Books](https://github.com/merewif/star-wars-loretracker/blob/main/public/data/books/Youtini%20Bookshelf%20-%20Canon%20Books.json)
[Legends Books](https://github.com/merewif/star-wars-loretracker/blob/main/public/data/books/Youtini%20Bookshelf%20-%20Legends%20Books.json)
[Canon Comics](https://github.com/merewif/star-wars-loretracker/blob/main/public/data/comics/Youtini%20Bookshelf%20-%20Canon%20Comics.json)
[Legends Comics (ABY)](https://github.com/merewif/star-wars-loretracker/blob/main/public/data/comics/Youtini%20Bookshelf%20-%20Legends%20Comics%20(ABY).json)
[Legends Comics (BBY)](https://github.com/merewif/star-wars-loretracker/blob/main/public/data/comics/Youtini%20Bookshelf%20-%20Legends%20Comics%20(BBY).json)

**Comment by merewif** [comment]
The issue was solved by @neeznamm [here](https://github.com/merewif/star-wars-loretracker/pull/29).
